services:
  - type: web
    name: ai-finance-management-system
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python init_db.py
    startCommand: gunicorn app:app
    envVars:
      - key: PORT
        value: 10000
      - key: SECRET_KEY
        generateValue: true
